### ISSUE TITLE
I2C

### ISSUE THREAD

**Issue by wqrwefdgfv** [maaad/RadSens1v2#7]
Hi!
Please add i2c interface option like bus_a /bus_b. I have several i2c devices such as oled, bme680 sensor, radsens, CG_Charger_BQ.
Thanks!

**Comment by maaad** [comment]
Check this out:
https://github.com/maaad/RadSens1v2/blob/cff53ae95ea4f97c4ab6795455bd4b87466690bd/_CG_RadSens.h#L9
