### ISSUE TITLE
ESP Home image compilation problem. 

### ISSUE THREAD

**Issue by cracrama** [maaad/RadSens1v2#8]
Good afternoon
Hope you ok. 

After recent ESPhome update (2023.9) During compilation of image file I'm receiveng below error:

`Generating partitions .pioenvs/1s/partitions.bin
Creating esp32 image...
Successfully created esp32 image.
In file included from src/main.cpp:109:
src/_CG_RadSens.h:3:10: fatal error: CountsPerMinute.h: No such file or directory

*************************************************************************
* Looking for CountsPerMinute.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:CountsPerMinute.h"
* Web  > https://registry.platformio.org/search?q=header:CountsPerMinute.h`

Below there is configuration which i use with RadSens v1.5 (I don't know how to set up sensitivity)

 - platform: custom
    lambda: |-
      auto rad_sens = new MyRadSens();
      App.register_component(rad_sens);
      return {rad_sens->IntensityDynamic_Sensor,rad_sens->IntensityStatic_Sensor, rad_sens->CurrentCPM_Sensor, rad_sens->MaxCPM_Sensor};
    sensors:
      - name: "Dynamic intensity"
        id: dynamic_intensity
        accuracy_decimals: 1
        unit_of_measurement: μR/h
        state_class: measurement
        filters: median
      - name: "Static intensity"
        accuracy_decimals: 1
        unit_of_measurement: μR/h
        id: rads1
        state_class: measurement
        filters: median
      - name: "Current CPM"
        accuracy_decimals: 1
        unit_of_measurement: CPM
        state_class: measurement
      - name: "Max CPM"
        accuracy_decimals: 1
        unit_of_measurement: CPM
        state_class: measurement

Please advise 
Kind regards

**Comment by maaad** [comment]
Check that you have latest version of [_CG_RadSens.h](https://github.com/maaad/RadSens1v2/blob/main/_CG_RadSens.h)

**Comment by cracrama** [comment]
Many thanks for response. 
Yes  you right - new version fixed issue. 
I though that CG_RadSens.h is automatically downloaded. 
Thanks again. 
Best regards
